import { Kit } from './types'

export const KITS: Kit[] = [
  // ── CLUBS ──────────────────────────────────────────────
  {
    id: 'man_utd',
    name: 'Manchester United',
    shortName: 'MAN UTD',
    type: 'club',
    badge: 'MU',
    primary: '#DA291C',
    secondary: '#FFFFFF',
    accent: '#FBE122',
    shorts: '#FFFFFF',
    socks: '#1A1A1A',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'real_madrid',
    name: 'Real Madrid',
    shortName: 'REAL MD',
    type: 'club',
    badge: 'RM',
    primary: '#FFFFFF',
    secondary: '#C4A44A',
    accent: '#C4A44A',
    shorts: '#FFFFFF',
    socks: '#FFFFFF',
    pattern: 'solid',
    collarColor: '#C4A44A',
    numberColor: '#1A1A1A',
  },
  {
    id: 'barcelona',
    name: 'FC Barcelona',
    shortName: 'BARCA',
    type: 'club',
    badge: 'FCB',
    primary: '#A50044',
    secondary: '#004D98',
    accent: '#FFED00',
    shorts: '#004D98',
    socks: '#004D98',
    pattern: 'stripes',
    stripeColor: '#004D98',
    collarColor: '#FFED00',
    numberColor: '#FFED00',
  },
  {
    id: 'liverpool',
    name: 'Liverpool FC',
    shortName: 'LFC',
    type: 'club',
    badge: 'LFC',
    primary: '#C8102E',
    secondary: '#00B2A9',
    accent: '#F6EB61',
    shorts: '#C8102E',
    socks: '#C8102E',
    pattern: 'solid',
    collarColor: '#00B2A9',
    numberColor: '#F6EB61',
  },
  {
    id: 'juventus',
    name: 'Juventus',
    shortName: 'JUVE',
    type: 'club',
    badge: 'JUV',
    primary: '#1A1A1A',
    secondary: '#FFFFFF',
    accent: '#FFFFFF',
    shorts: '#FFFFFF',
    socks: '#1A1A1A',
    pattern: 'stripes',
    stripeColor: '#FFFFFF',
    collarColor: '#1A1A1A',
    numberColor: '#FFFFFF',
  },
  {
    id: 'psg',
    name: 'Paris Saint-Germain',
    shortName: 'PSG',
    type: 'club',
    badge: 'PSG',
    primary: '#003F7F',
    secondary: '#DA291C',
    accent: '#FFFFFF',
    shorts: '#003F7F',
    socks: '#003F7F',
    pattern: 'sash',
    stripeColor: '#DA291C',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'bayern',
    name: 'Bayern Munich',
    shortName: 'BAYERN',
    type: 'club',
    badge: 'FCB',
    primary: '#DC052D',
    secondary: '#FFFFFF',
    accent: '#0066B2',
    shorts: '#FFFFFF',
    socks: '#DC052D',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'chelsea',
    name: 'Chelsea FC',
    shortName: 'CHELSEA',
    type: 'club',
    badge: 'CFC',
    primary: '#034694',
    secondary: '#FFFFFF',
    accent: '#DBA111',
    shorts: '#FFFFFF',
    socks: '#034694',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'ac_milan',
    name: 'AC Milan',
    shortName: 'AC MILAN',
    type: 'club',
    badge: 'ACM',
    primary: '#FB090B',
    secondary: '#1A1A1A',
    accent: '#FFFFFF',
    shorts: '#1A1A1A',
    socks: '#1A1A1A',
    pattern: 'stripes',
    stripeColor: '#1A1A1A',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'dortmund',
    name: 'Borussia Dortmund',
    shortName: 'BVB',
    type: 'club',
    badge: 'BVB',
    primary: '#FDE100',
    secondary: '#1A1A1A',
    accent: '#1A1A1A',
    shorts: '#1A1A1A',
    socks: '#FDE100',
    pattern: 'solid',
    collarColor: '#1A1A1A',
    numberColor: '#1A1A1A',
  },

  // ── COUNTRIES ──────────────────────────────────────────
  {
    id: 'brazil',
    name: 'Brazil',
    shortName: 'BRAZIL',
    type: 'country',
    badge: 'BRA',
    primary: '#FFDF00',
    secondary: '#009C3B',
    accent: '#002776',
    shorts: '#002776',
    socks: '#FFFFFF',
    pattern: 'solid',
    collarColor: '#009C3B',
    numberColor: '#002776',
  },
  {
    id: 'france',
    name: 'France',
    shortName: 'FRANCE',
    type: 'country',
    badge: 'FRA',
    primary: '#002395',
    secondary: '#FFFFFF',
    accent: '#ED2939',
    shorts: '#FFFFFF',
    socks: '#ED2939',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'germany',
    name: 'Germany',
    shortName: 'GERMANY',
    type: 'country',
    badge: 'GER',
    primary: '#FFFFFF',
    secondary: '#1A1A1A',
    accent: '#DD0000',
    shorts: '#FFFFFF',
    socks: '#FFFFFF',
    pattern: 'solid',
    collarColor: '#1A1A1A',
    numberColor: '#1A1A1A',
  },
  {
    id: 'argentina',
    name: 'Argentina',
    shortName: 'ARG',
    type: 'country',
    badge: 'ARG',
    primary: '#74ACDF',
    secondary: '#FFFFFF',
    accent: '#74ACDF',
    shorts: '#1A1A1A',
    socks: '#FFFFFF',
    pattern: 'stripes',
    stripeColor: '#FFFFFF',
    collarColor: '#74ACDF',
    numberColor: '#1A1A1A',
  },
  {
    id: 'england',
    name: 'England',
    shortName: 'ENGLAND',
    type: 'country',
    badge: 'ENG',
    primary: '#FFFFFF',
    secondary: '#CF081F',
    accent: '#CF081F',
    shorts: '#1A2B5A',
    socks: '#FFFFFF',
    pattern: 'solid',
    collarColor: '#CF081F',
    numberColor: '#1A1A1A',
  },
  {
    id: 'spain',
    name: 'Spain',
    shortName: 'SPAIN',
    type: 'country',
    badge: 'ESP',
    primary: '#AA151B',
    secondary: '#F1BF00',
    accent: '#F1BF00',
    shorts: '#1A2B5A',
    socks: '#AA151B',
    pattern: 'solid',
    collarColor: '#F1BF00',
    numberColor: '#FFFFFF',
  },
  {
    id: 'portugal',
    name: 'Portugal',
    shortName: 'PORTUGAL',
    type: 'country',
    badge: 'POR',
    primary: '#DA291C',
    secondary: '#006600',
    accent: '#FFFFFF',
    shorts: '#006600',
    socks: '#DA291C',
    pattern: 'solid',
    collarColor: '#006600',
    numberColor: '#FFFFFF',
  },
  {
    id: 'netherlands',
    name: 'Netherlands',
    shortName: 'HOLLAND',
    type: 'country',
    badge: 'NED',
    primary: '#FF6600',
    secondary: '#FFFFFF',
    accent: '#1A2B5A',
    shorts: '#FFFFFF',
    socks: '#FF6600',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
]

export const CLUB_KITS = KITS.filter(k => k.type === 'club')
export const COUNTRY_KITS = KITS.filter(k => k.type === 'country')
