import { Kit } from './types'

export const KITS: Kit[] = [
  // ── CLUBS ──────────────────────────────────────────────
  {
    id: 'man_utd',
    name: 'Manchester United',
    shortName: 'MAN UTD',
    type: 'club',
    badge: 'MU',
    primary: '#DA291C',
    secondary: '#FFFFFF',
    accent: '#FBE122',
    shorts: '#FFFFFF',
    socks: '#1A1A1A',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'real_madrid',
    name: 'Real Madrid',
    shortName: 'REAL MD',
    type: 'club',
    badge: 'RM',
    primary: '#FFFFFF',
    secondary: '#C4A44A',
    accent: '#C4A44A',
    shorts: '#FFFFFF',
    socks: '#FFFFFF',
    pattern: 'solid',
    collarColor: '#C4A44A',
    numberColor: '#1A1A1A',
  },
  {
    id: 'barcelona',
    name: 'FC Barcelona',
    shortName: 'BARCA',
    type: 'club',
    badge: 'FCB',
    primary: '#A50044',
    secondary: '#004D98',
    accent: '#FFED00',
    shorts: '#004D98',
    socks: '#004D98',
    pattern: 'stripes',
    stripeColor: '#004D98',
    collarColor: '#FFED00',
    numberColor: '#FFED00',
  },
  {
    id: 'liverpool',
    name: 'Liverpool FC',
    shortName: 'LFC',
    type: 'club',
    badge: 'LFC',
    primary: '#C8102E',
    secondary: '#00B2A9',
    accent: '#F6EB61',
    shorts: '#C8102E',
    socks: '#C8102E',
    pattern: 'solid',
    collarColor: '#00B2A9',
    numberColor: '#F6EB61',
  },
  {
    id: 'juventus',
    name: 'Juventus',
    shortName: 'JUVE',
    type: 'club',
    badge: 'JUV',
    primary: '#1A1A1A',
    secondary: '#FFFFFF',
    accent: '#FFFFFF',
    shorts: '#FFFFFF',
    socks: '#1A1A1A',
    pattern: 'stripes',
    stripeColor: '#FFFFFF',
    collarColor: '#1A1A1A',
    numberColor: '#FFFFFF',
  },
  {
    id: 'psg',
    name: 'Paris Saint-Germain',
    shortName: 'PSG',
    type: 'club',
    badge: 'PSG',
    primary: '#003F7F',
    secondary: '#DA291C',
    accent: '#FFFFFF',
    shorts: '#003F7F',
    socks: '#003F7F',
    pattern: 'sash',
    stripeColor: '#DA291C',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'bayern',
    name: 'Bayern Munich',
    shortName: 'BAYERN',
    type: 'club',
    badge: 'FCB',
    primary: '#DC052D',
    secondary: '#FFFFFF',
    accent: '#0066B2',
    shorts: '#FFFFFF',
    socks: '#DC052D',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'chelsea',
    name: 'Chelsea FC',
    shortName: 'CHELSEA',
    type: 'club',
    badge: 'CFC',
    primary: '#034694',
    secondary: '#FFFFFF',
    accent: '#DBA111',
    shorts: '#FFFFFF',
    socks: '#034694',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'ac_milan',
    name: 'AC Milan',
    shortName: 'AC MILAN',
    type: 'club',
    badge: 'ACM',
    primary: '#FB090B',
    secondary: '#1A1A1A',
    accent: '#FFFFFF',
    shorts: '#1A1A1A',
    socks: '#1A1A1A',
    pattern: 'stripes',
    stripeColor: '#1A1A1A',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'dortmund',
    name: 'Borussia Dortmund',
    shortName: 'BVB',
    type: 'club',
    badge: 'BVB',
    primary: '#FDE100',
    secondary: '#1A1A1A',
    accent: '#1A1A1A',
    shorts: '#1A1A1A',
    socks: '#FDE100',
    pattern: 'solid',
    collarColor: '#1A1A1A',
    numberColor: '#1A1A1A',
  },

  // ── COUNTRIES ──────────────────────────────────────────
  {
    id: 'brazil',
    name: 'Brazil',
    shortName: 'BRAZIL',
    type: 'country',
    badge: 'BRA',
    primary: '#FFDF00',
    secondary: '#009C3B',
    accent: '#002776',
    shorts: '#002776',
    socks: '#FFFFFF',
    pattern: 'solid',
    collarColor: '#009C3B',
    numberColor: '#002776',
  },
  {
    id: 'france',
    name: 'France',
    shortName: 'FRANCE',
    type: 'country',
    badge: 'FRA',
    primary: '#002395',
    secondary: '#FFFFFF',
    accent: '#ED2939',
    shorts: '#FFFFFF',
    socks: '#ED2939',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'germany',
    name: 'Germany',
    shortName: 'GERMANY',
    type: 'country',
    badge: 'GER',
    primary: '#FFFFFF',
    secondary: '#1A1A1A',
    accent: '#DD0000',
    shorts: '#FFFFFF',
    socks: '#FFFFFF',
    pattern: 'solid',
    collarColor: '#1A1A1A',
    numberColor: '#1A1A1A',
  },
  {
    id: 'argentina',
    name: 'Argentina',
    shortName: 'ARG',
    type: 'country',
    badge: 'ARG',
    primary: '#74ACDF',
    secondary: '#FFFFFF',
    accent: '#74ACDF',
    shorts: '#1A1A1A',
    socks: '#FFFFFF',
    pattern: 'stripes',
    stripeColor: '#FFFFFF',
    collarColor: '#74ACDF',
    numberColor: '#1A1A1A',
  },
  {
    id: 'england',
    name: 'England',
    shortName: 'ENGLAND',
    type: 'country',
    badge: 'ENG',
    primary: '#FFFFFF',
    secondary: '#CF081F',
    accent: '#CF081F',
    shorts: '#1A2B5A',
    socks: '#FFFFFF',
    pattern: 'solid',
    collarColor: '#CF081F',
    numberColor: '#1A1A1A',
  },
  {
    id: 'spain',
    name: 'Spain',
    shortName: 'SPAIN',
    type: 'country',
    badge: 'ESP',
    primary: '#AA151B',
    secondary: '#F1BF00',
    accent: '#F1BF00',
    shorts: '#1A2B5A',
    socks: '#AA151B',
    pattern: 'solid',
    collarColor: '#F1BF00',
    numberColor: '#FFFFFF',
  },
  {
    id: 'portugal',
    name: 'Portugal',
    shortName: 'PORTUGAL',
    type: 'country',
    badge: 'POR',
    primary: '#DA291C',
    secondary: '#006600',
    accent: '#FFFFFF',
    shorts: '#006600',
    socks: '#DA291C',
    pattern: 'solid',
    collarColor: '#006600',
    numberColor: '#FFFFFF',
  },
  {
    id: 'netherlands',
    name: 'Netherlands',
    shortName: 'HOLLAND',
    type: 'country',
    badge: 'NED',
    primary: '#FF6600',
    secondary: '#FFFFFF',
    accent: '#1A2B5A',
    shorts: '#FFFFFF',
    socks: '#FF6600',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  // ── 2026 FIFA WORLD CUP TEAMS ─────────────────────────────
  // Hosts
  {
    id: 'usa',
    name: 'United States',
    shortName: 'USA',
    type: 'country',
    badge: 'USA',
    primary: '#002868',
    secondary: '#BF0A30',
    accent: '#FFFFFF',
    shorts: '#002868',
    socks: '#BF0A30',
    pattern: 'solid',
    collarColor: '#BF0A30',
    numberColor: '#FFFFFF',
  },
  {
    id: 'canada',
    name: 'Canada',
    shortName: 'CANADA',
    type: 'country',
    badge: 'CAN',
    primary: '#FF0000',
    secondary: '#FFFFFF',
    accent: '#FF0000',
    shorts: '#FF0000',
    socks: '#FF0000',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'mexico',
    name: 'Mexico',
    shortName: 'MEXICO',
    type: 'country',
    badge: 'MEX',
    primary: '#006847',
    secondary: '#FFFFFF',
    accent: '#CE1126',
    shorts: '#006847',
    socks: '#006847',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  // UEFA
  {
    id: 'croatia',
    name: 'Croatia',
    shortName: 'CROATIA',
    type: 'country',
    badge: 'CRO',
    primary: '#FF0000',
    secondary: '#FFFFFF',
    accent: '#0093DD',
    shorts: '#FFFFFF',
    socks: '#FF0000',
    pattern: 'stripes',
    stripeColor: '#FFFFFF',
    collarColor: '#0093DD',
    numberColor: '#1A1A1A',
  },
  {
    id: 'denmark',
    name: 'Denmark',
    shortName: 'DENMARK',
    type: 'country',
    badge: 'DEN',
    primary: '#C60C30',
    secondary: '#FFFFFF',
    accent: '#C60C30',
    shorts: '#C60C30',
    socks: '#C60C30',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'austria',
    name: 'Austria',
    shortName: 'AUSTRIA',
    type: 'country',
    badge: 'AUT',
    primary: '#ED2939',
    secondary: '#FFFFFF',
    accent: '#ED2939',
    shorts: '#1A1A1A',
    socks: '#ED2939',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'switzerland',
    name: 'Switzerland',
    shortName: 'SWISS',
    type: 'country',
    badge: 'SUI',
    primary: '#FF0000',
    secondary: '#FFFFFF',
    accent: '#FF0000',
    shorts: '#FF0000',
    socks: '#FF0000',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'serbia',
    name: 'Serbia',
    shortName: 'SERBIA',
    type: 'country',
    badge: 'SRB',
    primary: '#C6363C',
    secondary: '#0C4076',
    accent: '#FFFFFF',
    shorts: '#0C4076',
    socks: '#C6363C',
    pattern: 'solid',
    collarColor: '#0C4076',
    numberColor: '#FFFFFF',
  },
  {
    id: 'romania',
    name: 'Romania',
    shortName: 'ROMANIA',
    type: 'country',
    badge: 'ROU',
    primary: '#002B7F',
    secondary: '#FCD116',
    accent: '#CE1126',
    shorts: '#002B7F',
    socks: '#FCD116',
    pattern: 'solid',
    collarColor: '#FCD116',
    numberColor: '#FCD116',
  },
  {
    id: 'belgium',
    name: 'Belgium',
    shortName: 'BELGIUM',
    type: 'country',
    badge: 'BEL',
    primary: '#ED2939',
    secondary: '#1A1A1A',
    accent: '#FAE042',
    shorts: '#ED2939',
    socks: '#1A1A1A',
    pattern: 'solid',
    collarColor: '#FAE042',
    numberColor: '#FAE042',
  },
  {
    id: 'turkey',
    name: 'Turkey',
    shortName: 'TURKEY',
    type: 'country',
    badge: 'TUR',
    primary: '#E30A17',
    secondary: '#FFFFFF',
    accent: '#E30A17',
    shorts: '#E30A17',
    socks: '#E30A17',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'albania',
    name: 'Albania',
    shortName: 'ALBANIA',
    type: 'country',
    badge: 'ALB',
    primary: '#E41E20',
    secondary: '#1A1A1A',
    accent: '#E41E20',
    shorts: '#1A1A1A',
    socks: '#E41E20',
    pattern: 'solid',
    collarColor: '#1A1A1A',
    numberColor: '#FFFFFF',
  },
  {
    id: 'czech_republic',
    name: 'Czech Republic',
    shortName: 'CZECHIA',
    type: 'country',
    badge: 'CZE',
    primary: '#FFFFFF',
    secondary: '#D7141A',
    accent: '#11457E',
    shorts: '#D7141A',
    socks: '#11457E',
    pattern: 'solid',
    collarColor: '#11457E',
    numberColor: '#1A1A1A',
  },
  {
    id: 'poland',
    name: 'Poland',
    shortName: 'POLAND',
    type: 'country',
    badge: 'POL',
    primary: '#FFFFFF',
    secondary: '#DC143C',
    accent: '#DC143C',
    shorts: '#DC143C',
    socks: '#FFFFFF',
    pattern: 'solid',
    collarColor: '#DC143C',
    numberColor: '#1A1A1A',
  },
  {
    id: 'slovakia',
    name: 'Slovakia',
    shortName: 'SLOVAKIA',
    type: 'country',
    badge: 'SVK',
    primary: '#FFFFFF',
    secondary: '#0B4EA2',
    accent: '#EE1C25',
    shorts: '#0B4EA2',
    socks: '#0B4EA2',
    pattern: 'solid',
    collarColor: '#EE1C25',
    numberColor: '#1A1A1A',
  },
  {
    id: 'hungary',
    name: 'Hungary',
    shortName: 'HUNGARY',
    type: 'country',
    badge: 'HUN',
    primary: '#CE2939',
    secondary: '#FFFFFF',
    accent: '#477050',
    shorts: '#CE2939',
    socks: '#FFFFFF',
    pattern: 'solid',
    collarColor: '#477050',
    numberColor: '#FFFFFF',
  },
  {
    id: 'ukraine',
    name: 'Ukraine',
    shortName: 'UKRAINE',
    type: 'country',
    badge: 'UKR',
    primary: '#FFD700',
    secondary: '#005BBB',
    accent: '#005BBB',
    shorts: '#005BBB',
    socks: '#FFD700',
    pattern: 'solid',
    collarColor: '#005BBB',
    numberColor: '#005BBB',
  },
  {
    id: 'scotland',
    name: 'Scotland',
    shortName: 'SCOTLAND',
    type: 'country',
    badge: 'SCO',
    primary: '#003DA5',
    secondary: '#FFFFFF',
    accent: '#003DA5',
    shorts: '#003DA5',
    socks: '#003DA5',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  // CONMEBOL
  {
    id: 'colombia',
    name: 'Colombia',
    shortName: 'COLOMBIA',
    type: 'country',
    badge: 'COL',
    primary: '#FCD116',
    secondary: '#003087',
    accent: '#CE1126',
    shorts: '#003087',
    socks: '#CE1126',
    pattern: 'solid',
    collarColor: '#003087',
    numberColor: '#003087',
  },
  {
    id: 'uruguay',
    name: 'Uruguay',
    shortName: 'URUGUAY',
    type: 'country',
    badge: 'URU',
    primary: '#75AADB',
    secondary: '#FFFFFF',
    accent: '#1A1A1A',
    shorts: '#1A1A1A',
    socks: '#75AADB',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#1A1A1A',
  },
  {
    id: 'ecuador',
    name: 'Ecuador',
    shortName: 'ECUADOR',
    type: 'country',
    badge: 'ECU',
    primary: '#FFD100',
    secondary: '#003DA5',
    accent: '#C8102E',
    shorts: '#003DA5',
    socks: '#003DA5',
    pattern: 'solid',
    collarColor: '#003DA5',
    numberColor: '#003DA5',
  },
  {
    id: 'paraguay',
    name: 'Paraguay',
    shortName: 'PARAGUAY',
    type: 'country',
    badge: 'PAR',
    primary: '#FFFFFF',
    secondary: '#D52B1E',
    accent: '#009A44',
    shorts: '#1A1A1A',
    socks: '#D52B1E',
    pattern: 'stripes',
    stripeColor: '#D52B1E',
    collarColor: '#009A44',
    numberColor: '#1A1A1A',
  },
  {
    id: 'venezuela',
    name: 'Venezuela',
    shortName: 'VENEZUEL',
    type: 'country',
    badge: 'VEN',
    primary: '#CF142B',
    secondary: '#003DA5',
    accent: '#FFD100',
    shorts: '#003DA5',
    socks: '#CF142B',
    pattern: 'solid',
    collarColor: '#FFD100',
    numberColor: '#FFFFFF',
  },
  // CONCACAF (non-hosts)
  {
    id: 'panama',
    name: 'Panama',
    shortName: 'PANAMA',
    type: 'country',
    badge: 'PAN',
    primary: '#FFFFFF',
    secondary: '#DA121A',
    accent: '#003893',
    shorts: '#003893',
    socks: '#003893',
    pattern: 'solid',
    collarColor: '#003893',
    numberColor: '#1A1A1A',
  },
  {
    id: 'costa_rica',
    name: 'Costa Rica',
    shortName: 'COSTA RC',
    type: 'country',
    badge: 'CRC',
    primary: '#002B7F',
    secondary: '#FFFFFF',
    accent: '#CE1126',
    shorts: '#002B7F',
    socks: '#CE1126',
    pattern: 'solid',
    collarColor: '#CE1126',
    numberColor: '#FFFFFF',
  },
  {
    id: 'honduras',
    name: 'Honduras',
    shortName: 'HONDURAS',
    type: 'country',
    badge: 'HON',
    primary: '#FFFFFF',
    secondary: '#0073CF',
    accent: '#0073CF',
    shorts: '#0073CF',
    socks: '#0073CF',
    pattern: 'solid',
    collarColor: '#0073CF',
    numberColor: '#1A1A1A',
  },
  // AFC
  {
    id: 'japan',
    name: 'Japan',
    shortName: 'JAPAN',
    type: 'country',
    badge: 'JPN',
    primary: '#003DA5',
    secondary: '#FFFFFF',
    accent: '#BC002D',
    shorts: '#FFFFFF',
    socks: '#003DA5',
    pattern: 'solid',
    collarColor: '#BC002D',
    numberColor: '#FFFFFF',
  },
  {
    id: 'south_korea',
    name: 'South Korea',
    shortName: 'S.KOREA',
    type: 'country',
    badge: 'KOR',
    primary: '#C60C30',
    secondary: '#FFFFFF',
    accent: '#003478',
    shorts: '#003478',
    socks: '#003478',
    pattern: 'solid',
    collarColor: '#003478',
    numberColor: '#FFFFFF',
  },
  {
    id: 'iran',
    name: 'Iran',
    shortName: 'IRAN',
    type: 'country',
    badge: 'IRN',
    primary: '#FFFFFF',
    secondary: '#239F40',
    accent: '#DA0000',
    shorts: '#239F40',
    socks: '#239F40',
    pattern: 'solid',
    collarColor: '#DA0000',
    numberColor: '#1A1A1A',
  },
  {
    id: 'australia',
    name: 'Australia',
    shortName: 'AUS',
    type: 'country',
    badge: 'AUS',
    primary: '#FFD700',
    secondary: '#00843D',
    accent: '#FFD700',
    shorts: '#00843D',
    socks: '#FFD700',
    pattern: 'solid',
    collarColor: '#00843D',
    numberColor: '#00843D',
  },
  {
    id: 'saudi_arabia',
    name: 'Saudi Arabia',
    shortName: 'S.ARABIA',
    type: 'country',
    badge: 'KSA',
    primary: '#006C35',
    secondary: '#FFFFFF',
    accent: '#006C35',
    shorts: '#FFFFFF',
    socks: '#006C35',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'iraq',
    name: 'Iraq',
    shortName: 'IRAQ',
    type: 'country',
    badge: 'IRQ',
    primary: '#CE1126',
    secondary: '#FFFFFF',
    accent: '#007A3D',
    shorts: '#1A1A1A',
    socks: '#CE1126',
    pattern: 'solid',
    collarColor: '#007A3D',
    numberColor: '#FFFFFF',
  },
  {
    id: 'uzbekistan',
    name: 'Uzbekistan',
    shortName: 'UZBEK',
    type: 'country',
    badge: 'UZB',
    primary: '#1EB53A',
    secondary: '#FFFFFF',
    accent: '#0099B5',
    shorts: '#1A1A1A',
    socks: '#1EB53A',
    pattern: 'solid',
    collarColor: '#0099B5',
    numberColor: '#FFFFFF',
  },
  {
    id: 'jordan',
    name: 'Jordan',
    shortName: 'JORDAN',
    type: 'country',
    badge: 'JOR',
    primary: '#007A3D',
    secondary: '#FFFFFF',
    accent: '#CE1126',
    shorts: '#1A1A1A',
    socks: '#007A3D',
    pattern: 'solid',
    collarColor: '#CE1126',
    numberColor: '#FFFFFF',
  },
  // CAF
  {
    id: 'morocco',
    name: 'Morocco',
    shortName: 'MOROCCO',
    type: 'country',
    badge: 'MAR',
    primary: '#C1272D',
    secondary: '#FFFFFF',
    accent: '#006233',
    shorts: '#1A1A1A',
    socks: '#C1272D',
    pattern: 'solid',
    collarColor: '#006233',
    numberColor: '#FFFFFF',
  },
  {
    id: 'senegal',
    name: 'Senegal',
    shortName: 'SENEGAL',
    type: 'country',
    badge: 'SEN',
    primary: '#FFFFFF',
    secondary: '#00853F',
    accent: '#FDEF42',
    shorts: '#FFFFFF',
    socks: '#00853F',
    pattern: 'solid',
    collarColor: '#00853F',
    numberColor: '#1A1A1A',
  },
  {
    id: 'egypt',
    name: 'Egypt',
    shortName: 'EGYPT',
    type: 'country',
    badge: 'EGY',
    primary: '#CE1126',
    secondary: '#FFFFFF',
    accent: '#CE1126',
    shorts: '#FFFFFF',
    socks: '#CE1126',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'nigeria',
    name: 'Nigeria',
    shortName: 'NIGERIA',
    type: 'country',
    badge: 'NGA',
    primary: '#008751',
    secondary: '#FFFFFF',
    accent: '#008751',
    shorts: '#FFFFFF',
    socks: '#008751',
    pattern: 'solid',
    collarColor: '#FFFFFF',
    numberColor: '#FFFFFF',
  },
  {
    id: 'cameroon',
    name: 'Cameroon',
    shortName: 'CAMEROON',
    type: 'country',
    badge: 'CMR',
    primary: '#007A5E',
    secondary: '#CE1126',
    accent: '#FCD116',
    shorts: '#CE1126',
    socks: '#FCD116',
    pattern: 'solid',
    collarColor: '#FCD116',
    numberColor: '#FCD116',
  },
  {
    id: 'ivory_coast',
    name: 'Ivory Coast',
    shortName: 'IVORY CT',
    type: 'country',
    badge: 'CIV',
    primary: '#F77F00',
    secondary: '#FFFFFF',
    accent: '#009A44',
    shorts: '#FFFFFF',
    socks: '#F77F00',
    pattern: 'solid',
    collarColor: '#009A44',
    numberColor: '#1A1A1A',
  },
  {
    id: 'south_africa',
    name: 'South Africa',
    shortName: 'S.AFRICA',
    type: 'country',
    badge: 'RSA',
    primary: '#007A4D',
    secondary: '#FFB81C',
    accent: '#E03C31',
    shorts: '#1A1A1A',
    socks: '#FFB81C',
    pattern: 'solid',
    collarColor: '#FFB81C',
    numberColor: '#FFB81C',
  },
  {
    id: 'mali',
    name: 'Mali',
    shortName: 'MALI',
    type: 'country',
    badge: 'MLI',
    primary: '#14B53A',
    secondary: '#FFFFFF',
    accent: '#CE1126',
    shorts: '#FFFFFF',
    socks: '#14B53A',
    pattern: 'solid',
    collarColor: '#CE1126',
    numberColor: '#1A1A1A',
  },
  {
    id: 'algeria',
    name: 'Algeria',
    shortName: 'ALGERIA',
    type: 'country',
    badge: 'ALG',
    primary: '#FFFFFF',
    secondary: '#006233',
    accent: '#D21034',
    shorts: '#FFFFFF',
    socks: '#FFFFFF',
    pattern: 'solid',
    collarColor: '#006233',
    numberColor: '#1A1A1A',
  },
  // OFC
  {
    id: 'new_zealand',
    name: 'New Zealand',
    shortName: 'NZ',
    type: 'country',
    badge: 'NZL',
    primary: '#FFFFFF',
    secondary: '#00247D',
    accent: '#CC142B',
    shorts: '#1A1A1A',
    socks: '#00247D',
    pattern: 'solid',
    collarColor: '#CC142B',
    numberColor: '#1A1A1A',
  },
]

export const CLUB_KITS = KITS.filter(k => k.type === 'club')
export const COUNTRY_KITS = KITS.filter(k => k.type === 'country')
